изменения для первого тестового самообновления
skbkontur/cement pull request #140
Opened 2022-05-11 13:42 UTC by szagidullina

1 этап. Подключено обновление из локальной папки (для тестирования)

2022-05-12 06:47 UTC, ArXa1L requested changes

2022-05-12 06:47 UTC, ArXa1L commented on Commands/SelfUpdate.cs
> +cmd=""$path""
mono потерялся

2022-05-12 06:47 UTC, ArXa1L commented on Commands/SelfUpdate.cs
> +            // var updater = server == null
это ж только для тестов было, если мы такое зарелизим - потеряем автообновление

2022-05-12 06:47 UTC, ArXa1L commented on Commands/SelfUpdate.cs
> +                if (diff <= TimeSpan.FromMinutes(30))
зачем?

2022-05-12 06:47 UTC, ArXa1L commented on Common/CementFromLocalPathUpdater.cs
> +                log.LogError($"Fail self-update, exception: '{ex}' ");
exception нужно передавать первым аргументом в LogError, а в сообщении опционально можно залоггироваться ex.Message. В дополнение к этому необходимо убрать интерполяцию и сделать placeholder + дополнительный аргумент метода

2022-05-12 06:47 UTC, ArXa1L commented on Common/CementFromLocalPathUpdater.cs
> +                using (FileStream fsSource = new FileStream(
а чего не using var?

2022-05-12 06:47 UTC, ArXa1L commented on Common/CementFromLocalPathUpdater.cs
> +                    byte[] zipContent = new byte[fsSource.Length];
обычно мы объявляем переменные с var, без явного указания типа (компилятор сам разберется, а конкретно в этом месте это не влияет на читаемость кода)

2022-05-12 06:47 UTC, ArXa1L commented on Common/CementFromLocalPathUpdater.cs
> +                        int n = fsSource.Read(zipContent, numBytesRead, numBytesToRead);
n - некорректное название переменной, нужно сделать что то осмысленное

2022-05-12 06:47 UTC, ArXa1L commented on Commands/SelfUpdate.cs
> -	rm ~/bin/dotnet/cm_new.exe
Теперь папка с новым релизом не будет чистится вообще?

2022-05-12 06:47 UTC, ArXa1L commented on Commands/SelfUpdate.cs
> +            // var cm = Path.Combine(from, "cm.exe");
Если этот код не нужен - его нужно удалить

2022-05-12 06:47 UTC, ArXa1L commented on Common/CementFromLocalPathUpdater.cs
> +    public class CementFromLocalPathUpdater : ICementUpdater
нужно поменять public на internal и добавить sealed

2022-05-13 08:20 UTC, madetara commented on Commands/SelfUpdate.cs
> +cmd=""$usingMono $path""
Кажется тут нужно убрать пробел между `$usingMono` и `$path`. Иначе, если у нас в usingMono будет пустая строка, команда будет иметь вид ` cm` (условно), и это может сломаться

2022-05-13 08:32 UTC, madetara commented on Commands/SelfUpdate.cs
> +                Log.LogError(exception, "Auto update failed, error: '{errorMessage}'", exception.Message);
На будущее: плейсхолдеры должны быть в UpperCamelCase, т.е. например `{ErrorMessage}` вместо `{errorMessage}`

Тут в целом ситуация с логами довольно грустная, так что можешь не поправлять. Но если поправишь будет хорошо

2022-05-13 08:33 UTC, madetara commented on Commands/SelfUpdate.cs
> +                Log.LogError(exception, "Auto update failed, error: '{errorMessage}'", exception.Message);
То же самое в строках 84 и 222

2022-05-13 08:35 UTC, madetara requested changes
Написал несколько небольших замечаний. Одно, на мой взгляд, критичное

2022-05-13 09:05 UTC, madetara approved these changes

2022-05-13 11:37 UTC, ArXa1L approved these changes

2022-05-13 12:10 UTC, merged