migrate to .net6
skbkontur/cement pull request #146
Opened 2022-05-16 16:32 UTC by szagidullina

2 этап

2022-05-18 07:21 UTC, ArXa1L requested changes

2022-05-18 07:21 UTC, ArXa1L commented on Commands/SelfUpdate.cs
> +                case PlatformID.Unix: return "linux-x64";
Еще можно использовать switch expression

2022-05-18 07:21 UTC, ArXa1L commented on Commands/SelfUpdate.cs
> +            if (Directory.Exists(Path.Combine(from, currOsDir)))
Я поверхностно читал этот код и не смог быстро понять что он делает =(

2022-05-18 09:18 UTC, szagidullina commented on .gitignore
> +/files-common/linux-x64/cm
готово

2022-05-18 09:29 UTC, szagidullina commented on Cement.Net/App.config
>  ﻿<?xml version="1.0" encoding="utf-8"?>
config убрала, работает и без него, а на счет вмешательства старого конфига на новую версию не понятно, пока не вмешивался, все работало

2022-05-18 09:29 UTC, szagidullina commented on Cement.Net/CementEntry.csproj
> +		<Copyright>Copyright © 2019</Copyright>
готово

2022-05-18 09:31 UTC, szagidullina commented on Cement.Net/CementEntry.csproj
> +		<Version>4.1.0</Version>
5.1.0 ? готово

2022-05-18 09:34 UTC, szagidullina commented on Commands/Commands.csproj
> +      <HintPath>..\externals\NuGet.dll</HintPath>
готово

2022-05-18 09:35 UTC, szagidullina commented on Commands/Commands.csproj
> +  <ItemGroup>
готово

2022-05-18 09:36 UTC, szagidullina commented on Commands/SelfUpdate.cs
> +using net.r_eg.MvsSln.Extensions;
уже не нужен, удалила

2022-05-18 09:37 UTC, szagidullina commented on Commands/SelfUpdate.cs
> +                if (CementSettings.Get().EnabledSelfUpdate != true)
готово

2022-05-18 09:39 UTC, szagidullina commented on Commands/SelfUpdate.cs
> +            var updater = server == null
готово

2022-05-18 09:53 UTC, szagidullina commented on Commands/SelfUpdate.cs
> +            if (Directory.Exists(Path.Combine(from, currOsDir)))
подкорректировала название переменных. Тут мы исключаем лишние папки и файлы из cement.zip, копируем на обновление только конкретные файлы из конкретной папки соответствующей OS.

2022-05-18 09:54 UTC, szagidullina commented on Commands/SelfUpdate.cs
> +            if (Directory.Exists(Path.Combine(from, currOsDir)))
Иначе автообновления не происходит и приходится ручками запускать скрипт bin/cm для замены старого cm.exe на новый

2022-05-20 12:28 UTC, madetara commented on Cement.Net/App.config
>  ﻿<?xml version="1.0" encoding="utf-8"?>
В итоге всё же оставили конфиг?

2022-05-20 12:28 UTC, madetara commented on Cement.Net/CementEntry.csproj
> +		<AssemblyName>cm</AssemblyName>
Имя сборки поменялось. Ничего не сломается от этого?

2022-05-20 12:30 UTC, madetara commented on Cement.Net/CementEntry.csproj
> -  <Target Name="CopyExe" AfterTargets="Build" DependsOnTargets="Merge" Condition="'$(OS)' != 'Unix'">
А этот таргет точно не нужен? Кажется он отвечал за установку цемента при самостоятельной сборке

2022-05-20 12:37 UTC, KoHHeKT commented on Cement.Net/CementEntry.csproj
> -  <Target Name="CopyExe" AfterTargets="Build" DependsOnTargets="Merge" Condition="'$(OS)' != 'Unix'">
На мой взгляд, CopyExe - зло, он тебе ломает локально установленный цемент без возможностей восстановления, если проект не билдится. Если хочется быструю локальную установку для дебага, то надо сделать, чтобы она была с возможностью отката или через создание временного окружения(здоровый вариант - поставить цемент во временную папку, запустить консоль и передать пути до дебажной версии цемента. Но для этого надо сделать в самом цементе поддержку portable-инсталляции и отвязку от статических путей).

2022-05-20 13:10 UTC, madetara commented on Common/CementFromServerUpdater.cs
> +#pragma warning disable SYSLIB0014
Может попробуем переделать сразу на `HttpClient` если это не очень сложно? Вместо того чтобы ворнинги глушить

2022-05-20 13:10 UTC, madetara commented on Common/CementFromServerUpdater.cs
> +#pragma warning disable SYSLIB0014
То же самое в строке 50

2022-05-20 13:11 UTC, madetara commented on Common/Common.csproj
> +  <ItemGroup>
Это выглядит странно. Кажется мы голосом обсуждали что надо просто удалить файл физически, а эту `ItemGroup` убрать

2022-05-20 13:22 UTC, madetara commented on Common/Helper.cs
> +                log.LogWarning("Found old key {OldKey} in {JoinArgs} in {DirectoryPath}", oldKey, string.Join(" ", args), Directory.GetCurrentDirectory());
`JoinArgs` странный плейсхолдер. Давай переименуем во что-то более говорящее

2022-05-20 13:23 UTC, madetara commented on Common/ShellRunner.cs
> +            var quote = '"';
На это нужно обратить внимание

2022-05-20 13:24 UTC, madetara commented on Common/Usages.cs
> +#pragma warning disable SYSLIB0014
То же что и [тут](https://github.com/skbkontur/cement/pull/146/files#r878128229)

2022-05-20 13:25 UTC, madetara commented on Dockerfile
> +RUN ../cement/dotnet/cm.exe init
Давай пока этот докерфайл не будем трогать. Его по-хорошему надо полностью переписать, в том числе поменяв базовый образ, раз mono больше не нужен

2022-05-20 13:26 UTC, madetara commented on README.md
> +RUN ~/bin/dotnet/cm.exe reinstall
Тоже не уверен что этот докерфайл рабочий, пока предлагаю оставить как есть

2022-05-20 13:29 UTC, madetara commented on appveyor.yml
> +  - dotnet publish -r linux-x64 -o ..\files-common\linux-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:DebugType=None --self-contained true
У тебя тут на выходе по идее будет не .exe файл, а дальше в некоторых скриптах ожидается .exe
Надо разобраться и сделать единообразно

2022-05-20 13:29 UTC, madetara commented on global.json
> +}
Это файл кажется не нужен. Подозреваю что его добавила утилита конвертации в .NET 6. Попробуем удалить?

2022-05-20 13:30 UTC, madetara commented on scripts/start_publish.cmd
> +timeout 2
Что за загадочный файл?

2022-05-20 13:33 UTC, madetara commented on Commands/SelfUpdate.cs
> -namespace Commands
Подобные имзенения кодстайла лучше делать отдельным коммитом, потому что мне сейчас очень тяжело понять, менялась ли в этом файле логика.

Сейчас есть два варианта:
1. Откатить file-scoped namespace
2. Описать изменения в этом файле, чтобы я мог проверить

2022-05-20 13:35 UTC, madetara requested changes
Выглядит хорошо. Есть несколько замечаний, в основном по стилю. 
Нужно обратить особое внимание на SelfUpdate.cs, скрипты обновления и публикации

2022-05-20 13:36 UTC, madetara commented on Cement.Net/CementEntry.csproj
> -  <Target Name="CopyExe" AfterTargets="Build" DependsOnTargets="Merge" Condition="'$(OS)' != 'Unix'">
Согласен, но я ждал ответа от авторки PR 😄

2022-05-20 13:46 UTC, madetara commented on Commands/SelfUpdate.cs
> +            var updater = server == null
В итоге всё же решили не указывать явно тип или коммит потерялся где-то?

2022-05-20 13:48 UTC, madetara commented on Commands/SelfUpdate.cs
> +                case PlatformID.Unix: return "linux-x64";
Кажется тут из-за клинапа произошёл file-scoped namespace и теперь совсем непонятно что изменилось 😢

2022-05-20 13:51 UTC, madetara commented on Common/ShellRunner.cs
> +                        threadOutput.Interrupt();
На это нужно обратить внимание

2022-05-20 13:53 UTC, madetara commented on Cement.Net/CementEntry.csproj
> +		<Version>4.1.0</Version>
Наверное 5.0.0 логичнее было бы

2022-05-23 07:52 UTC, madetara commented on Common/CementFromServerUpdater.cs
> +                var client = new HttpClient();
Давай наверное всё же откатим эти изменения. Тут слишком много нужно дополнительно править, выделим в отдельную задачу

2022-05-23 09:18 UTC, madetara commented on Common/ShellRunner.cs
> +                        threadOutput.Interrupt();
Комментарий

> метод Abort нужен был для прерывания потока (вызовом соответствующего exception внутри потока), в dotnet 6 этот метод не реализован (устарел). Чтобы выполнить эту функцию в коде, устаревший Abort заменила на метод Interrupt(), который тоже выбрасывает исключение внутри потока, но чтобы он сработал, нужно чтобы поток был в статусе WaitJoinSleep, поэтому, сначала вызываю в потоке метод Join(), затем Interrupt(), а затем снова блокировку Join() чтобы основной поток смог завершиться и убить запущенный процесс.

2022-05-23 09:20 UTC, madetara commented on Common/ShellRunner.cs
> +            var quote = '"';
Комментарий

> В .NET 6 вызов с одинарной кавычкой под Linux разваливается

2022-07-06 18:03 UTC, closed without merging