изменения для первого самообновления
skbkontur/cement pull request #148
Opened 2022-05-19 13:11 UTC by szagidullina

2022-05-19 14:36 UTC, madetara commented on Commands/SelfUpdate.cs
> +        private string GetCurrentOsDirectory()
Предлагаю этот метод, и все где остальные где возможно, сделать `static`

2022-05-19 14:37 UTC, madetara commented on Commands/SelfUpdate.cs
> +        private IList<string> SetInstallFilesForCopy(string from, string currOsDir)
Методы называют `Set...` если они что-то изменяют (устанавливают, если переводить дословно). Наш метод получает список файлов, так что логичнее было бы начать его со слова `Get`

2022-05-19 14:37 UTC, szagidullina commented on Common/CementSettings.cs
> +        public bool? EnabledSelfUpdate;
готово

2022-05-19 14:38 UTC, madetara commented on Commands/SelfUpdate.cs
> +        private IList<string> SetInstallFilesForCopy(string from, string currOsDir)
Возвращаемый тип лучше сделать `IEnumerable`, т.к. он более общий и нам не нужны ограничения, накладываемые интерфейсом `IList`. Потом можно будет поменять, если возникнет необходимость

2022-05-19 14:39 UTC, madetara commented on Commands/SelfUpdate.cs
> +            IList<string> includeFiles = SetInstallFilesForCopy(from, currOsDir);
У нас принято использовать `var` при объявлении переменных, если компилятор не требует явно указывать тип

2022-05-19 14:40 UTC, szagidullina commented on Commands/SelfUpdate.cs
> +        private string GetCurrentOsDirectory()
готово

2022-05-19 14:41 UTC, szagidullina commented on Commands/SelfUpdate.cs
> +        private IList<string> SetInstallFilesForCopy(string from, string currOsDir)
готово

2022-05-19 14:42 UTC, szagidullina commented on Commands/SelfUpdate.cs
> +            IList<string> includeFiles = SetInstallFilesForCopy(from, currOsDir);
готово

2022-05-19 14:45 UTC, madetara commented on Commands/SelfUpdate.cs
> +            var pathCurrOsDir = Path.Combine(from, currOsDir);
Я бы внёс сюда вызов метода, вместо объявления отдельной переменной и переименовал саму переменную. Мы же тут по сути находим папку с цементом, так что на мой взгляд название типа `pathToCementBinary` было бы более корректным

2022-05-19 14:47 UTC, madetara commented on Commands/SelfUpdate.cs
> +                var isOsWin = (Environment.OSVersion.Platform != PlatformID.Unix)&&(Environment.OSVersion.Platform != PlatformID.MacOSX);
Я бы вынес в метод. Условие достаточно громоздкое, на мой взгляд

И ещё там есть `PlatformID.Xbox` который тоже надо бы учесть. Шансов что кто-то решит туда поставить cement конечно довольно мало, но для общности пусть лучше будет

2022-05-19 14:48 UTC, madetara commented on Commands/SelfUpdate.cs
> +                cm = Path.Combine(pathCurrOsDir, string.Format("cm{0}", isOsWin ? ".exe": ""));
Давай тут лучше интерполяцию используем вместо `string.Format`

2022-05-19 14:49 UTC, madetara commented on Commands/SelfUpdate.cs
> +            if (!IsInstallingCement && File.Exists(Path.Combine(dotnetInstallFolder, "cm.exe")))
Тут кажется нужно учесть что у нас не всегда будет .exe файл

2022-05-19 14:52 UTC, madetara commented on Commands/SelfUpdate.cs
> +            File.Copy(cm, cmNew, true);
Почему мы тут копируем файл, а в следующей строке пытаемся его удалить?

2022-05-19 14:55 UTC, madetara requested changes
В общем выглядит хорошо. Есть пара замечаний по стилю. И я бы добавил логов чтобы мы могли понять, если что-то пошло не так

2022-05-19 15:08 UTC, szagidullina commented on Commands/SelfUpdate.cs
> +            if (!IsInstallingCement && File.Exists(Path.Combine(dotnetInstallFolder, "cm.exe")))
Здесь как раз всегда .exe

2022-05-19 15:08 UTC, madetara commented on Commands/SelfUpdate.cs
> +            var pathCurrOsDir = Path.Combine(from, currOsDir);
Я имел в виду, внести `GetCurrentOsDirectory()` в `Path.Combine` 

Но заметил что эта переменная дальше используется, так что это предложение отменется :)

2022-05-19 15:11 UTC, madetara commented on Commands/SelfUpdate.cs
> +            if (!IsInstallingCement && File.Exists(Path.Combine(dotnetInstallFolder, "cm.exe")))
А, мы же и под unix переименовываем в .exe

Тогда кажется ты права

2022-05-19 15:23 UTC, szagidullina commented on Commands/SelfUpdate.cs
> +            IList<string> includeFiles = SetInstallFilesForCopy(from, currOsDir);
подкорректировала

2022-05-19 16:25 UTC, madetara commented on Commands/SelfUpdate.cs
> +        private static bool CheckIsWindowsPlatform()
Тут нужно убрать слово `Check` и оставить просто `IsWindowsPlatform` по аналогии с логическими переменными

2022-05-19 16:25 UTC, madetara commented on Commands/SelfUpdate.cs
> +            var tempPathToCementBinary = Path.Combine(from, currOsDir);;
Лишняя точка с запятой

2022-05-19 16:26 UTC, madetara requested changes
Осталась пара косметических замечений и будет готово

2022-05-19 16:35 UTC, szagidullina commented on Commands/SelfUpdate.cs
> +            var tempPathToCementBinary = Path.Combine(from, currOsDir);;
готово

2022-05-19 16:35 UTC, szagidullina commented on Commands/SelfUpdate.cs
> +        private static bool CheckIsWindowsPlatform()
готово

2022-05-20 06:28 UTC, madetara approved these changes

2022-05-20 06:29 UTC, merged